(() => {
  const API_BASE='https://www.thesportsdb.com/api/v1/json/3/searchteams.php?t=',CACHE_KEY='agendaTraderClubBadgesV2';
  const memory=new Map(),pending=new Map();let persistent={};
  const aliases={fla:'Flamengo',fluminense:'Fluminense',flu:'Fluminense',pal:'Palmeiras',por:'Palmeiras',cor:'Corinthians',sccp:'Corinthians',sao:'São Paulo',spfc:'São Paulo',san:'Santos',santos:'Santos',cru:'Cruzeiro',cam:'Atlético Mineiro',galo:'Atlético Mineiro',cap:'Athletico Paranaense',athletico:'Athletico Paranaense',athletic:'Athletic Club MG',crb:'CRB',vas:'Vasco da Gama',bot:'Botafogo',gre:'Grêmio',gremio:'Grêmio',int:'Internacional',inter:'Internacional',bah:'Bahia',for:'Fortaleza',cea:'Ceará',ceara:'Ceará',spo:'Sport Recife',sport:'Sport Recife',vit:'Vitória',vitoria:'Vitória',cui:'Cuiabá',bra:'Red Bull Bragantino',bragantino:'Red Bull Bragantino',juventude:'Juventude',juf:'Juventude',goi:'Goiás',goias:'Goiás',ath:'Athletic Club MG',ame:'América Mineiro',america:'América Mineiro',ava:'Avaí',cha:'Chapecoense',ponte:'Ponte Preta',gua:'Guarani',nov:'Novorizontino',remo:'Remo',paysandu:'Paysandu',pai:'Paysandu'};
  try{persistent=JSON.parse(localStorage.getItem(CACHE_KEY)||'{}')||{}}catch(_){persistent={}}
  const normalize=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const initials=(n='')=>String(n).trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase().slice(0,3)||'?';
  const canonicalName=n=>aliases[normalize(n)]||String(n||'').trim();
  let saveTimer=0;function saveCache(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{localStorage.setItem(CACHE_KEY,JSON.stringify(persistent))}catch(_){}},500)}
  function teamScore(t,n){const w=normalize(n),names=[t.strTeam,t.strTeamShort,t.strAlternate].filter(Boolean).map(normalize);let s=names.includes(w)?100:names.some(x=>x.startsWith(w)||w.startsWith(x))?72:names.some(x=>x.includes(w)||w.includes(x))?52:0;if(normalize(t.strCountry)==='brazil')s+=32;if(normalize(t.strSport)!=='soccer')s-=100;return s}
  function bestTeam(ts,n){return Array.isArray(ts)&&ts.length?[...ts].sort((a,b)=>teamScore(b,n)-teamScore(a,n))[0]:null}
  async function lookup(name){const typed=String(name||'').trim();if(typed.length<2)return null;const query=canonicalName(typed),key=normalize(query);if(memory.has(key))return memory.get(key);if(Object.prototype.hasOwnProperty.call(persistent,key)){memory.set(key,persistent[key]);return persistent[key]}if(pending.has(key))return pending.get(key);const task=(async()=>{try{const r=await fetch(API_BASE+encodeURIComponent(query),{cache:'force-cache'});if(!r.ok)throw 0;const d=await r.json(),t=bestTeam(d?.teams,query),info=t?.strBadge?{name:t.strTeam||query,badge:t.strBadge,id:t.idTeam||'',country:t.strCountry||''}:null;memory.set(key,info);persistent[key]=info;saveCache();return info}catch(_){return null}finally{pending.delete(key)}})();pending.set(key,task);return task}
  function ensureDatalist(input,side){const id='clubSuggestions_'+side;let d=document.getElementById(id);if(!d){d=document.createElement('datalist');d.id=id;document.body.appendChild(d)}input.setAttribute('list',id);return d}
  function updateSuggestions(d,v){const q=normalize(v);d.innerHTML=[...new Set(Object.entries(aliases).filter(([a,n])=>a.startsWith(q)||normalize(n).startsWith(q)).map(([,n])=>n))].slice(0,8).map(n=>`<option value="${escapeHtml(n)}"></option>`).join('')}
  function ensurePreview(input,side){const id='clubBadgePreview_'+side;let e=document.getElementById(id);if(!e){e=document.createElement('div');e.id=id;e.style.cssText='display:none;align-items:center;gap:8px;margin-top:7px;font-size:12px;color:#718096;min-height:30px';input.insertAdjacentElement('afterend',e)}return e}
  function renderPreview(e,info,typed){if(!typed?.trim()||typed.trim().length<2){e.style.display='none';e.innerHTML='';return}e.style.display='flex';e.innerHTML=info?.badge?`<img src="${escapeHtml(info.badge)}" alt="" loading="lazy" decoding="async" style="width:30px;height:30px;object-fit:contain;border-radius:7px;background:#fff;padding:2px;border:1px solid #e5e7eb"><span>${escapeHtml(info.name||typed)}</span>`:`<span style="width:30px;height:30px;display:grid;place-items:center;border-radius:7px;background:#eef2f7;color:#64748b;font-weight:800">${escapeHtml(initials(typed))}</span><span>Escudo não encontrado</span>`}
  function wireInput(id,side){const input=document.getElementById(id);if(!input||input.dataset.badgeWired==='1')return;input.dataset.badgeWired='1';const preview=ensurePreview(input,side),dl=ensureDatalist(input,side);let timer=0,seq=0;const run=()=>{clearTimeout(timer);const value=input.value;updateSuggestions(dl,value);const my=++seq;if(value.trim().length<2){renderPreview(preview,null,'');return}timer=setTimeout(async()=>{const info=await lookup(value);if(my===seq&&input.value===value)renderPreview(preview,info,value)},500)};input.addEventListener('input',run,{passive:true});input.addEventListener('change',run);input.addEventListener('blur',()=>{const full=aliases[normalize(input.value)];if(full){input.value=full;input.dispatchEvent(new Event('input',{bubbles:true}))}else run()});if(input.value.trim())run()}
  function splitMatch(text){const raw=String(text||'').replace(/\s+/g,' ').trim();for(const sep of [' × ',' x ',' X ',' vs ',' VS ',' - ']){const i=raw.indexOf(sep);if(i>0)return[raw.slice(0,i).trim(),raw.slice(i+sep.length).trim()]}return null}
  function findMatchTextNode(el){const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){if(n.parentElement?.closest('.club-match-badges'))continue;if(splitMatch(n.nodeValue))return n}return null}
  function buildBadgeNode(info,name){const w=document.createElement('span');w.style.cssText='display:inline-flex;align-items:center;gap:8px;min-width:0';if(info?.badge){const i=document.createElement('img');i.src=info.badge;i.alt='';i.loading='lazy';i.decoding='async';i.style.cssText='width:38px;height:38px;object-fit:contain;flex:0 0 38px';i.onerror=()=>i.style.display='none';w.appendChild(i)}else{const f=document.createElement('span');f.textContent=initials(name);f.style.cssText='width:38px;height:38px;border-radius:50%;display:grid;place-items:center;flex:0 0 38px;background:#eef2f7;color:#64748b;font-size:11px;font-weight:850';w.appendChild(f)}const l=document.createElement('span');l.textContent=name;w.appendChild(l);return w}
  async function enhanceMatch(el){if(!el||el.dataset.badgesBusy==='1'||el.querySelector('.club-match-badges'))return;const node=findMatchTextNode(el);if(!node)return;const m=splitMatch(node.nodeValue);if(!m)return;const [home,away]=m,sig=normalize(home)+'|'+normalize(away);if(el.dataset.badgesSig===sig)return;el.dataset.badgesBusy='1';const[h,a]=await Promise.all([lookup(home),lookup(away)]);if(!el.isConnected)return;el.dataset.badgesBusy='0';el.dataset.badgesSig=sig;const row=document.createElement('span');row.className='club-match-badges';row.style.cssText='display:inline-flex;align-items:center;gap:8px;flex-wrap:wrap;margin-right:10px';row.append(buildBadgeNode(h,home));const x=document.createElement('span');x.textContent='×';x.style.cssText='color:#94a3b8;font-weight:700';row.append(x,buildBadgeNode(a,away));if(node.isConnected)node.parentNode.replaceChild(row,node)}
  function enhanceRoot(root=document){root.querySelectorAll?.('#listaAgenda .jogo-confronto,#listaHistorico .jogo-confronto').forEach(enhanceMatch)}
  let queued=false,roots=new Set();function schedule(root){if(root?.nodeType===1)roots.add(root);if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;wireInput('mandante','mandante');wireInput('visitante','visitante');if(!roots.size)enhanceRoot();else{for(const r of roots){if(r.matches?.('.jogo-confronto'))enhanceMatch(r);else enhanceRoot(r)}roots.clear()}})}
  function boot(){wireInput('mandante','mandante');wireInput('visitante','visitante');enhanceRoot();const target=document.querySelector('.container')||document.body,new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)schedule(n)}).observe(target,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();