(() => {
 const CONFIG_KEY='agendaTraderConfig';let lastSignature='';
 function getConfig(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')||{}}catch(_){return{}}}
 function saveConfig(c){localStorage.setItem(CONFIG_KEY,JSON.stringify(c));try{if(typeof agendarSyncNuvem==='function')agendarSyncNuvem()}catch(_){}}
 function renameHome(){const b=document.querySelector('nav button');if(b&&b.textContent.trim()!=='Início')b.textContent='Início'}
 function initials(){const c=getConfig(),n=(c.nomeUsuario||'').trim(),e=(document.getElementById('contaEmail')?.textContent||'').trim(),s=n||e||'U';return s.split(/\s+|@/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('').slice(0,2)||'U'}
 function photoMarkup(size=48){const p=getConfig().profilePhoto||'';return p?`<img src="${p}" alt="Foto de perfil">`:`<div class="profile-initials">${initials()}</div>`}
 function renderTopProfile(force=false){const h=document.querySelector('header');if(!h)return;document.querySelector('.conta-barra .profile-photo-sidebar')?.remove();let b=h.querySelector('.profile-photo-top');if(!b){b=document.createElement('div');b.className='profile-photo-top';h.prepend(b)}const c=getConfig(),sig=(c.profilePhoto||'')+'|'+initials();if(force||sig!==lastSignature){b.innerHTML=photoMarkup();lastSignature=sig}}
 function ensureSettingsCard(){const s=document.getElementById('configuracoes');if(!s||document.getElementById('profilePhotoCard'))return;const c=document.createElement('div');c.className='card';c.id='profilePhotoCard';c.innerHTML=`<h3>Perfil da conta</h3><div style="display:flex;align-items:center;gap:16px;flex-wrap:wrap"><div id="profilePhotoPreview"></div><div style="flex:1;min-width:220px"><div class="info" style="margin-bottom:10px">Escolha uma foto do seu celular ou computador. Ela fica salva junto com as configurações da sua conta.</div><div class="acoes" style="margin-top:0"><label class="btn-blue" style="display:inline-flex;align-items:center;cursor:pointer;margin:0">Escolher foto<input id="profilePhotoInput" type="file" accept="image/jpeg,image/png,image/webp" style="display:none"></label><button id="profilePhotoRemove" class="btn-gray" type="button">Remover foto</button></div><div id="profilePhotoStatus" class="nota" style="margin-top:9px"></div></div></div>`;const a=[...s.querySelectorAll('.card')].find(x=>/Aparência/i.test(x.querySelector('h3')?.textContent||''));if(a)a.insertAdjacentElement('afterend',c);else s.appendChild(c);document.getElementById('profilePhotoInput')?.addEventListener('change',handlePhoto);document.getElementById('profilePhotoRemove')?.addEventListener('click',removePhoto);renderSettingsPhoto()}
 function renderSettingsPhoto(){const p=document.getElementById('profilePhotoPreview');if(!p)return;const c=getConfig();p.innerHTML=c.profilePhoto?`<img src="${c.profilePhoto}" style="width:82px;height:82px;border-radius:50%;object-fit:cover;border:2px solid white;box-shadow:0 0 0 1px #dbe3ee">`:`<div style="width:82px;height:82px;border-radius:50%;display:grid;place-items:center;background:#eaf2ff;color:#2563eb;font-weight:900">${initials()}</div>`}
 function compressImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(new Error('Não foi possível ler a imagem.'));r.onload=()=>{const i=new Image();i.onerror=()=>rej(new Error('Imagem inválida.'));i.onload=()=>{const s=256,c=document.createElement('canvas');c.width=s;c.height=s;const x=c.getContext('2d'),k=Math.max(s/i.width,s/i.height),w=i.width*k,h=i.height*k;x.drawImage(i,(s-w)/2,(s-h)/2,w,h);res(c.toDataURL('image/jpeg',.82))};i.src=r.result};r.readAsDataURL(file)})}
 async function handlePhoto(e){const f=e.target.files?.[0];if(!f)return;const st=document.getElementById('profilePhotoStatus');try{if(!/^image\/(jpeg|png|webp)$/i.test(f.type))throw new Error('Use uma imagem JPG, PNG ou WEBP.');if(f.size>12*1024*1024)throw new Error('Escolha uma foto de até 12 MB.');if(st)st.textContent='Processando foto...';const d=await compressImage(f),c=getConfig();c.profilePhoto=d;saveConfig(c);renderTopProfile(true);renderSettingsPhoto();if(st)st.textContent='✅ Foto salva e sincronizada.'}catch(err){if(st)st.textContent='❌ '+err.message}e.target.value=''}
 function removePhoto(){const c=getConfig();delete c.profilePhoto;saveConfig(c);renderTopProfile(true);renderSettingsPhoto();const s=document.getElementById('profilePhotoStatus');if(s)s.textContent='Foto removida.'}
 function preservePhoto(){if(typeof window.salvarConfiguracoes!=='function'||window.salvarConfiguracoes.__profileWrapped)return;const o=window.salvarConfiguracoes,w=function(){const b=getConfig(),p=b.profilePhoto||'',r=o.apply(this,arguments);if(p){const a=getConfig();if(!a.profilePhoto){a.profilePhoto=p;saveConfig(a)}}renderTopProfile(true);renderSettingsPhoto();return r};w.__profileWrapped=true;window.salvarConfiguracoes=w}
 const style=document.createElement('style');style.textContent=`
 .conta-barra::before{display:none!important;content:none!important}
 @media(min-width:901px){body header{height:118px!important;padding:17px 14px!important;display:grid!important;grid-template-columns:48px 1fr!important;grid-template-rows:auto auto!important;column-gap:11px!important;row-gap:3px!important;text-align:left!important;align-content:center!important;overflow:visible!important}body header::before{display:none!important;content:none!important}body header .profile-photo-top{grid-column:1!important;grid-row:1/3!important;width:48px!important;height:48px!important;align-self:center!important;border-radius:50%!important;overflow:hidden!important}body header .profile-photo-top img,body header .profile-photo-top .profile-initials{width:48px!important;height:48px!important;border-radius:50%!important;object-fit:cover!important;display:grid!important;place-items:center!important;background:#eaf2ff!important;color:#2563eb!important;font-weight:900!important;border:2px solid #fff!important;box-shadow:0 0 0 1px #dbe3ee!important;box-sizing:border-box!important}body header h1{grid-column:2!important;grid-row:1!important;margin:0!important;padding:0!important;line-height:1.05!important;min-width:0!important;align-self:end!important}body header h1 #tituloNome{font-size:20px!important;display:block!important;white-space:normal!important;overflow:visible!important;text-overflow:clip!important;word-break:normal!important}body header small{grid-column:2!important;grid-row:2!important;margin:1px 0 0!important;padding:0!important;max-width:170px!important;font-size:9.5px!important;line-height:1.25!important;white-space:normal!important;overflow:visible!important;align-self:start!important}body nav{top:118px!important}}
 @media(max-width:900px){body header{display:grid!important;grid-template-columns:44px 1fr!important;grid-template-rows:auto auto!important;gap:2px 9px!important;text-align:left!important;overflow:visible!important}body header .profile-photo-top{grid-column:1!important;grid-row:1/3!important;width:44px!important;height:44px!important;overflow:hidden!important;border-radius:50%!important}body header .profile-photo-top img,body header .profile-photo-top .profile-initials{width:44px!important;height:44px!important;border-radius:50%!important;object-fit:cover!important;display:grid!important;place-items:center!important;background:#eaf2ff!important;color:#2563eb!important;font-weight:900!important}body header h1{grid-column:2!important;grid-row:1!important;margin:0!important}body header h1 #tituloNome{white-space:normal!important;overflow:visible!important;text-overflow:clip!important}body header small{grid-column:2!important;grid-row:2!important;margin:0!important;white-space:normal!important;overflow:visible!important}}
 `;document.head.appendChild(style);
 function refresh(){renameHome();preservePhoto();ensureSettingsCard();renderTopProfile();renderSettingsPhoto()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(refresh,0));else setTimeout(refresh,0);window.addEventListener('storage',e=>{if(e.key===CONFIG_KEY)refresh()});window.addEventListener('focus',refresh);
})();